In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

import pandas as pd
import time

In [9]:
data = pd.read_csv('/home/zaibachkhoa/Downloads/export-as-csv-20241106062517.csv')
data

       STT                  Tên bài hát           Tác giả             Thể loại
0        1            Lướt Sóng Đạp Mây          Thiên Tú    Nhạc Hoa Lời Việt
1        2             Nối lại tình xưa           Vinh Sử               Bolero
2        3                  Vạn Lối Sầu         Quang Lập               Bolero
3        4         Đừng Hỏi Em Ổn Không      Jin Tuấn Nam                  Pop
4        5              Tạ từ trong đêm  Trần Thiện Thanh               Bolero
...    ...                          ...               ...                  ...
4257  4258            Hình Bóng Mẹ Hiền           Giác An    Phật giáo|Giác An
4258  4259            Điệu Ru Đêm Thánh         Vĩnh Phúc        Nhạc thánh ca
4259  4260        Khi trái tim biết yêu          Khúc Lan  Nhạc ngoại lời Việt
4260  4261     Chuyện tình hoa cát đằng         Hà Phương               Bolero
4261  4262  Bến tre thơm ngát hương dừa         Minh Thùy                Ca cổ

[4262 rows x 4 columns]

In [10]:
duplicate_rows = data.duplicated(subset=['Tên bài hát'])
data.loc[data.duplicated(subset=['Tên bài hát'])]
data.loc[data['Tên bài hát'] == 'Ngày em đi']
data_ = data.drop_duplicates(subset=['Tên bài hát'])
data_.loc[:, 'Tên bài hát']
data_

       STT                  Tên bài hát           Tác giả             Thể loại
0        1            Lướt Sóng Đạp Mây          Thiên Tú    Nhạc Hoa Lời Việt
1        2             Nối lại tình xưa           Vinh Sử               Bolero
2        3                  Vạn Lối Sầu         Quang Lập               Bolero
3        4         Đừng Hỏi Em Ổn Không      Jin Tuấn Nam                  Pop
4        5              Tạ từ trong đêm  Trần Thiện Thanh               Bolero
...    ...                          ...               ...                  ...
4257  4258            Hình Bóng Mẹ Hiền           Giác An    Phật giáo|Giác An
4258  4259            Điệu Ru Đêm Thánh         Vĩnh Phúc        Nhạc thánh ca
4259  4260        Khi trái tim biết yêu          Khúc Lan  Nhạc ngoại lời Việt
4260  4261     Chuyện tình hoa cát đằng         Hà Phương               Bolero
4261  4262  Bến tre thơm ngát hương dừa         Minh Thùy                Ca cổ

[4095 rows x 4 columns]

In [11]:
# data_['cột mới'] = None 
# # data_.loc[5, 'cột mới'] = 3
# # data_.head(7)
# # # data_[data_['cột mới'] == 3]
tenbaihat_tacgia = (data_['Tên bài hát'] + ' ' + data_['Tác giả']).tolist()

/tmp/ipykernel_91292/2963137122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_['cột mới'] = None

,STT,Tên bài hát,Tác giả,Thể loại,cột mới
0,1,Lướt Sóng Đạp Mây,Thiên Tú,Nhạc Hoa Lời Việt,None
1,2,Nối lại tình xưa,Vinh Sử,Bolero,None
2,3,Vạn Lối Sầu,Quang Lập,Bolero,None
3,4,Đừng Hỏi Em Ổn Không,Jin Tuấn Nam,Pop,None
4,5,Tạ từ trong đêm,Trần Thiện Thanh,Bolero,None
...,...,...,...,...,...
4257,4258,Hình Bóng Mẹ Hiền,Giác An,Phật giáo|Giác An,None
4258,4259,Điệu Ru Đêm Thánh,Vĩnh Phúc,Nhạc thánh ca,None
4259,4260,Khi trái tim biết yêu,Khúc Lan,Nhạc ngoại lời Việt,None
4260,4261,Chuyện tình hoa cát đằng,Hà Phương,Bolero,None
4261,4262,Bến tre thơm ngát hương dừa,Minh Thùy,Ca cổ,None

In [5]:
chrome_service = Service(executable_path='/home/zaibachkhoa/Documents/TikTok/chromedriver-linux64/chromedriver')
driver = webdriver.Chrome(service=chrome_service)

In [8]:
# driver.get('https://www.tiktok.com/search?q=m%E1%BB%99t%20v%C3%B2ng%20vi%E1%BB%87t%20nam%20t%C3%B9ng%20d%C6%B0%C6%A1ng&t=1730863323637')

In [11]:
# for t2 in tenbaihat_tacgia:
def loop(row):
    driver.get('https://www.tiktok.com/foryou')
    time.sleep(2)
    khungtimkiem = driver.find_element(By.XPATH, '//form[@data-e2e="search-box"]//input')
    khungtimkiem.send_keys(row['Tên bài hát'] + ' ' + row['Tác giả'])
    input('####################################')
    khungtimkiem.send_keys(Keys.RETURN)
    for _ in range(3):
        time.sleep(1)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    samgiongzon = driver.find_elements(By.XPATH, '//div[@data-e2e="search_top-item"]//a')
    print(len(samgiongzon))
    linklist = list()
    for elem in samgiongzon:
        linklist.append(elem.get_attribute('href'))
        print(linklist[-1])

    for link in linklist:
        time.sleep(1)
        driver.execute_script("window.open('');")
        driver.switch_to.window(driver.window_handles[-1])
        driver.get(link)
        input('press Enter!')
    
        newtab = driver.find_element(By.XPATH, '//h1[@data-e2e="browse-video-desc"]')
        input(data_[data_['Tên bài hát'] == row['Tên bài hát']])
        data_[data_['Tên bài hát'] == row['Tên bài hát']]['2'] = newtab.text
        print('2:', newtab.text)
        newtab = driver.find_element(By.XPATH, '//h4[@data-e2e="browse-music"]')
        data_[data_['Tên bài hát'] == row['Tên bài hát']]['3'] = newtab.text
        print('3:', newtab.text)
    
        time.sleep(2)
        driver.close()
        driver.switch_to.window(driver.window_handles[0])

In [12]:
# for _ in range(3):
#     time.sleep(1)
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [13]:
# samgiongzon = driver.find_elements(By.XPATH, '//div[@data-e2e="search_top-item"]//a')

In [14]:
# print(len(samgiongzon))
# linklist = list()
# for elem in samgiongzon:
#     linklist.append(elem.get_attribute('href'))
#     print(linklist[-1])

40
https://www.tiktok.com/@melodyofthelover/video/7392003672999267601
https://www.tiktok.com/@melodyofthelover/video/7419904355287010578
https://www.tiktok.com/@_d.hoangvu_official_/video/7199968322174078234
https://www.tiktok.com/@_d.hoangvu_official_/video/7293517269664058626
https://www.tiktok.com/@ngocnubolero_/video/7135030819265023258
https://www.tiktok.com/@du.khc.nhc.vng/video/7374499191264906513
https://www.tiktok.com/@hathedungmusic/video/7425501394834099464
https://www.tiktok.com/@melodyofthelover/video/7371731318759116033
https://www.tiktok.com/@melodyofthelover/video/7419903551830248722
https://www.tiktok.com/@melodyofthelover/video/7371816749978701073
https://www.tiktok.com/@nhaccongkhapnoi/video/7142321724866972955
https://www.tiktok.com/@tuyetngan0107n/video/7391492707320876304
https://www.tiktok.com/@nguyen_lam2807/video/7346093412984032514
https://www.tiktok.com/@chillwithartofficial/video/7401063841225870608
https://www.tiktok.com/@vualidon884/video/7345064614201216263
https://www.tiktok.com/@nhacthapnien1975/video/7306548935751896322
https://www.tiktok.com/@dongphuongbao.68/video/7275696264228932866
https://www.tiktok.com/@family.tuongvy91/video/7391441691233881352
https://www.tiktok.com/@yeu.karaoke/video/7348192529830956290
https://www.tiktok.com/@chi4music/video/7318359354674023682
https://www.tiktok.com/@vinhthuyenkim_music/video/7272352945474129159
https://www.tiktok.com/@kimdong678/video/7346150377949007111
https://www.tiktok.com/@chillwithartofficial/video/7401063645356035345
https://www.tiktok.com/@thuongrobosts9/video/7165850520282778907
https://www.tiktok.com/@qtnp.97/video/7291634594330283265
https://www.tiktok.com/@family.tuongvy91/video/7392423680350948616
https://www.tiktok.com/@chi4music/video/7316870550612167937
https://www.tiktok.com/@lamtuyen.1987/video/7173506416815115546
https://www.tiktok.com/@yeuboleroxua/video/6936389617952296194
https://www.tiktok.com/@kyuctuoithouave/video/7019274216189054234
https://www.tiktok.com/@qtnp.97/video/7291632435689688322
https://www.tiktok.com/@trungvo20891/video/7020259808519490843
https://www.tiktok.com/@tus.011/video/7370155119431716103
https://www.tiktok.com/@nguyenngoc5193/video/7359177785182637328
https://www.tiktok.com/@huynhxuandai12345/video/7262690524220460289
https://www.tiktok.com/@khuuhuyvu/video/7144278835238800666
https://www.tiktok.com/@truongkien20/video/7371825383278202119
https://www.tiktok.com/@yaabang_1874/video/7145379855104740634
https://www.tiktok.com/@thanhdoentertainment/video/7130943750896979227
https://www.tiktok.com/@_congchuacaugiay_08/video/7367348541225700624

In [15]:
# for link in linklist:
#     time.sleep(1)
#     driver.execute_script("window.open('');")
#     driver.switch_to.window(driver.window_handles[-1])
#     driver.get(link)
#     input('press Enter!')

#     newtab = driver.find_element(By.XPATH, '//h1[@data-e2e="browse-video-desc"]')
#     print('2:', newtab.text)
#     newtab = driver.find_element(By.XPATH, '//h4[@data-e2e="browse-music"]')
#     print('3:', newtab.text)

#     time.sleep(2)
#     driver.close()
#     driver.switch_to.window(driver.window_handles[0])

press Enter!

2: Về đây bên nhau ta nối lại tình xưa | Nối Lại Tình Xưa | Sáng tác: Vinh Sử - Ngân Giang #noilaitinhxua #bolero #learnontiktok #guitarcover #lyrics #guitartab #nhuquynh #manhquynh
3: nhạc nền - Melody of The Lover

press Enter!

2: Về đây bên nhau ta nối lại tình xưa | NỐI LẠI TÌNH XƯA | Sáng tác: Vinh Sử - Ngân Giang | FL Studio #noilaitinhxua #flstudio #manhquynh #nhuquynh
3: nhạc nền - Melody of The Lover

KeyboardInterrupt: Interrupted by user

In [ ]:
# driver.execute_script("window.open('');")
# driver.switch_to.window(driver.window_handles[-1])
# driver.get(linklist[1])

In [ ]:
# driver.switch_to.window(driver.window_handles[0])

In [ ]:
# newtab = driver.find_element(By.XPATH, '//h1[@data-e2e="browse-video-desc"]')
# print('2:', newtab.text)
# newtab = driver.find_element(By.XPATH, '//h4[@data-e2e="browse-music"]')
# print('3:', newtab.text)